### ISSUE TITLE
Different objects with same resources map same keys to different resources

### ISSUE THREAD

**Issue by mojtabaAmir** [andrasq/consistent-hash-js#1]
We have some servers get resources from same API and use consistent hash to map user tokens in our cache servers.
Our server map keys to different cache nodes!

**Comment by andrasq** [comment]
Are servers being added to / removed from the hash ring while the system is running?  Do you have a small exampe?

What you describe can happen if the node closest to the hash of the resource name changes, like when the closest node is removed, or a new node is inserted even closer to to the hash.

**Comment by andrasq** [comment]
Another possibility is that the key strings appear the same visually but have different bit patterns (either because they include non-printing characters or because they have characters that look similar but with different encodings.)

**Comment by mojtabaAmir** [comment]
We have two servers and I want any objects of hash ring have same resource for same key
Sample code:

```
const ConsistentHash = require('consistent-hash')

function randomStr(length) {
  var result           = '';
  var characters       = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  for ( var i = 0; i < length; i++ ) {
    result += characters.charAt(Math.floor(Math.random() * characters.length));
  }
  return result;
}

const randomStrings = []
for (let i = 0; i < 100; i++)
  randomStrings.push(randomStr(10))

const cH = new ConsistentHash()

cH.add(1)
cH.add(2)
cH.add(3)

console.log(cH.get(randomStrings[0]))
console.log(cH.get(randomStrings[10]))
console.log(cH.get(randomStrings[20]))

const cH2 = new ConsistentHash()

cH2.add(1)
cH2.add(2)
cH2.add(3)

console.log(cH2.get(randomStrings[0]))
console.log(cH2.get(randomStrings[10]))
console.log(cH2.get(randomStrings[20]))
```

**Comment by andrasq** [comment]
I see what you mean, yes, the code could handle that better.  I'll see if I can add that behavior as a constructor option.  Currently one has to configure that use case by passing in the control points along with the nodes; the control points and range together specify the location of the nodes around the hash ring.

**Comment by mojtabaAmir** [comment]
Thanks.
